### ISSUE TITLE
catalina貌似引导不了啊

### ISSUE THREAD

**Issue by kasisi** [Joehaivo/hackintosh#2]
还有压缩文件mac自带的归档工具打不开，需要第三方的解压缩软件才行

**Comment by Joehaivo** [comment]
文件我已经重新上传了， 无法引导的话看一下是不是主板和cpu跟我一样

**Comment by kasisi** [comment]
主板是一样的，cpu是9100f，有独显应该也不是问题
你的bios版本是多少，晚上我再回去试一下

**Comment by Joehaivo** [comment]
bios是P1.20

**Comment by kasisi** [comment]
最新的bios都是4.1了，我的好像是4.0，而且4.0之后也不能降级，估计与这个有关了

**Comment by wujunze** [comment]
你好 是 Clove 引导 还是  OC 引导 @Joehaivo

**Comment by Joehaivo** [comment]
clover

**Comment by wujunze** [comment]
> clover

我用 Clover 引导成功了   OC 引导试了三次引导失败
